module Types
  class MutationType < Types::BaseObject
    field :login, mutation: Mutations::LoginMutation
    field :register, mutation: Mutations::RegisterMutation
    field :create_manual_account, mutation: Mutations::CreateManualAccount
    field :create_transaction, mutation: Mutations::CreateTransaction
    field :update_transaction, mutation: Mutations::UpdateTransaction
    field :bulk_categorize, mutation: Mutations::BulkCategorize
    field :create_category, mutation: Mutations::CreateCategory
    field :update_category, mutation: Mutations::UpdateCategory
    field :delete_category, mutation: Mutations::DeleteCategory
    field :create_tag, mutation: Mutations::CreateTag
    field :update_budget_item, mutation: Mutations::UpdateBudgetItem
    field :delete_budget_item, mutation: Mutations::DeleteBudgetItem
    field :copy_budget_from_month, mutation: Mutations::CopyBudgetFromMonth
    field :fill_budget_from_averages, mutation: Mutations::FillBudgetFromAverages
    field :create_plaid_link_token, mutation: Mutations::CreatePlaidLinkToken
    field :exchange_plaid_token, mutation: Mutations::ExchangePlaidToken
    field :create_categorization_rule, mutation: Mutations::CreateCategorizationRule
    field :update_categorization_rule, mutation: Mutations::UpdateCategorizationRule
    field :delete_categorization_rule, mutation: Mutations::DeleteCategorizationRule
    field :apply_categorization_rules, mutation: Mutations::ApplyCategorizationRules
    field :detect_recurring_transactions, mutation: Mutations::DetectRecurringTransactions
    field :create_recurring_item, mutation: Mutations::CreateRecurringItem
    field :update_recurring_item, mutation: Mutations::UpdateRecurringItem
    field :delete_recurring_item, mutation: Mutations::DeleteRecurringItem
    field :mark_recurring_item_paid, mutation: Mutations::MarkRecurringItemPaid
    field :create_goal, mutation: Mutations::CreateGoal
    field :update_goal, mutation: Mutations::UpdateGoal
    field :delete_goal, mutation: Mutations::DeleteGoal
    field :update_profile, mutation: Mutations::UpdateProfile
    field :change_password, mutation: Mutations::ChangePassword
    field :invite_to_household, mutation: Mutations::InviteToHousehold
    field :accept_invitation, mutation: Mutations::AcceptInvitation
    field :remove_household_member, mutation: Mutations::RemoveHouseholdMember
    field :import_csv, mutation: Mutations::ImportCsv
    field :bulk_transaction_action, mutation: Mutations::BulkTransactionAction
    field :split_transaction, mutation: Mutations::SplitTransaction
    field :detect_transfers, mutation: Mutations::DetectTransfers
    field :link_transfer, mutation: Mutations::LinkTransfer
    field :update_household, mutation: Mutations::UpdateHousehold
    field :update_notification_preference, mutation: Mutations::UpdateNotificationPreference
    field :mark_notification_read, mutation: Mutations::MarkNotificationRead
    field :mark_all_notifications_read, mutation: Mutations::MarkAllNotificationsRead
    field :update_tag, mutation: Mutations::UpdateTag
    field :delete_tag, mutation: Mutations::DeleteTag
    field :share_account, mutation: Mutations::ShareAccount
    field :adjust_balance, mutation: Mutations::AdjustBalance
    field :upload_receipt, mutation: Mutations::UploadReceipt
    field :upload_statement, mutation: Mutations::UploadStatement
  end
end
